### PR TITLE
Adding javadoc for AcknowledgableDelivery

### PR DESCRIPTION
**Pull request by NickTsitlakidis**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@NickTsitlakidis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-rabbitmq&pullRequestId=39)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-rabbitmq&pullRequestId=39) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@NickTsitlakidis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-rabbitmq&pullRequestId=39)!

**Comment by NickTsitlakidis** [comment]
Any thoughts on why this is failing during the apt install stage?

**Comment by acogoluegnes** [comment]
I don't know, maybe a network glitch, some builds ran successfully yesterday, and nothing has changed since then. Accepting anyway, as this is just Javadoc. Thanks!

**Pull request merged**
