### PR TITLE
[FIX] Channels are leaking when CancelCallback is used

### PR DESCRIPTION
**Pull request by pmackowski**
Hi, 
Channels are leaking when cancelCallback is called in `Receiver#consumeXXX` methods 
```
final String consumerTag = channel.basicConsume(queue, true, deliverCallback, cancelCallback);
```
`consumerTag` is no longer available and `channel.basicCancel(consumerTag)` method fails with exception:

**Error while closing channel: Unknown consumerTag**

As a result channel.close() is not invoked.

PS. Thank you for mentioning me in the documentation. It is a pleasure to contribute to this library. If you have any ideas how to make it even better, please create an issue so I can contribute more.

### CODE REVIEW

**Comment by acogoluegnes** [comment]
Good catch, thanks for the fix. Your feedback and high-quality contributions are much appreciated!

**Comment by acogoluegnes** [comment]
@pmackowski As per your proposition to contribute even more :-)  @smaldini created a couple of issues recently #63 #64. Feel free to have a look and contribute a PR, thanks!

**Comment by pmackowski** [comment]
@acogoluegnes Sure, I will take [#63](https://github.com/reactor/reactor-rabbitmq/issues/63)

**Comment by acogoluegnes** [comment]
@pmackowski Awesome, thanks!

**Pull request merged**
