### PR TITLE
use `delaySubscription` to declare a queue

### PR DESCRIPTION
**Pull request by bsideup**

### CODE REVIEW

**Comment by michaelklishin** [comment]
@bsideup it would be nice to have at least a single sentence justification for this change. What problem are we addressing here and why?

**Comment by bsideup** [comment]
@michaelklishin users are confused by `thenMany` and think that they can't receive messages without a sender.

`delaySubscription` is more idiomatic and reads as "delay the subscription until the queue is defined".

**Comment by michaelklishin** [comment]
Welp, I don't have the permissions to merge this 😃. Arnaud is on holiday this week so this may have to wait for a few days. Thank you!

**Comment by bsideup** [comment]
@michaelklishin no problem or rush, that's just a suggestion anyways :)

**Pull request merged**
